apiVersion: v1
kind: Service
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  type: NodePort
  selector:
    app: backend-api
  ports:
  - name: api-backend-port
    port: 1234
    targetPort: 8080
    # protocol: TCP
    nodePort: 32001
  
